### ISSUE TITLE
一首歌曲播放过程中，直接播放另一首个会报一下异常信息。

### ISSUE THREAD

**Issue by andy-ho** [Bowenduan/BowenMusic#1]
`Exception in thread Thread-41:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File ".\src\MusicCmd.py", line 464, in __play_pl_base
    self.player.wait_for_playback()
  File "C:\Users\andrew.he\AppData\Roaming\Python\Python37\site-packages\mpv.py", line 912, in wait_for_playback
    self.wait_for_event('end_file')
  File "C:\Users\andrew.he\AppData\Roaming\Python\Python37\site-packages\mpv.py", line 969, in wait_for_event
    pass
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\contextlib.py", line 119, in __exit__
    next(self.gen)
  File "C:\Users\andrew.he\AppData\Roaming\Python\Python37\site-packages\mpv.py", line 1000, in prepare_and_wait_for_event
    self.check_core_alive()
  File "C:\Users\andrew.he\AppData\Roaming\Python\Python37\site-packages\mpv.py", line 901, in check_core_alive
    raise ShutdownError('libmpv core has been shutdown')
mpv.ShutdownError: libmpv core has been shutdown`

**Comment by andy-ho** [comment]
MusicCmd.py

**Comment by Bowen-n** [comment]
In function `__play_pl_base`,
Change `self.player.wait_for_playback()` to `self.player.wait_for_shutdown()` .
[Check here](https://github.com/Bowenduan/BowenMusic/commit/68360589b8fe976c810765fe38f0ea6ce3114735)

```python
    def __play_pl_base(self, url):
        self.player.play(url)
        # self.player.wait_for_playback()
        self.player.wait_for_shutdown()
        self.current_song = None
        self.event_pl.set()
```

Thanks.😁
